#!/usr/bin/env python3
from __future__ import annotations

import csv
import json
from pathlib import Path
from typing import Dict, Iterable, List


ROOT = Path(__file__).resolve().parents[2]
DATA = ROOT / "paper" / "tables" / "data"
OUT_MD = ROOT / "paper" / "tables" / "tcslu_aaai2027_tables.md"
OUT_JSON = DATA / "tcslu_aaai2027_table_snapshot.json"


def read_csv(path: Path) -> List[Dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def markdown_table(rows: Iterable[Dict[str, str]], columns: List[str]) -> str:
    material = list(rows)
    if not material:
        return "_No rows._\n"
    header = "| " + " | ".join(columns) + " |"
    sep = "| " + " | ".join("---" for _ in columns) + " |"
    body = []
    for row in material:
        body.append("| " + " | ".join(str(row.get(col, "") or "") for col in columns) + " |")
    return "\n".join([header, sep, *body]) + "\n"


def main() -> None:
    current = read_csv(DATA / "tcslu_current_replacement_status.csv")
    registry = read_csv(DATA / "tcslu_experiment_registry.csv")
    peers = read_csv(DATA / "tcslu_peer_spiking_transformer_comparison.csv")
    lookup_cost_path = DATA / "lookup_cost_proxy.csv"
    lookup_cost = read_csv(lookup_cost_path) if lookup_cost_path.exists() else []

    completed = [row for row in current if row["status"].startswith("completed")]
    planned_main = [row for row in registry if row["table"] == "main"]
    planned_ablation = [row for row in registry if row["table"] == "ablation"]
    planned_robustness = [row for row in registry if row["table"] in {"robustness", "generalization"}]

    lines = [
        "# TCSLU AAAI2027 Tables",
        "",
        "Generated by `scripts/local/build_tcslu_aaai_tables.py`.",
        "Rows marked `planned` are preregistered targets, not results.",
        "",
        "## Current Replacement Status",
        "",
        markdown_table(
            completed,
            [
                "architecture",
                "dataset",
                "time_steps",
                "method",
                "clean_top1",
                "injected_top1",
                "drop_top1",
                "hit_rate",
                "memory_kib",
                "role",
            ],
        ),
        "## Metadata-Inclusive Lookup Cost Proxy",
        "",
        (
            "This table is analytical accounting only, not a measured SRAM, "
            "latency, energy, or hardware-cycle result. It is generated by "
            "`scripts/local/build_lookup_cost_proxy_tables.py`."
        ),
        "",
        markdown_table(
            lookup_cost,
            [
                "family",
                "setting",
                "table_name",
                "supported_entries",
                "address_bits",
                "prototype_only_fp32_kib",
                "sparse_fp32_u32key_u16count_kib",
                "dense_fp32_with_valid_bit_kib",
                "lookup_count_vs_original_macs",
            ],
        ),
        "## Main Experiment Registry",
        "",
        markdown_table(
            planned_main,
            [
                "experiment_id",
                "architecture",
                "dataset",
                "time_steps",
                "methods",
                "primary_metric",
                "matched_controls",
                "success_gate",
            ],
        ),
        "## Ablation Registry",
        "",
        markdown_table(
            planned_ablation,
            [
                "experiment_id",
                "architecture",
                "dataset",
                "methods",
                "primary_metric",
                "matched_controls",
                "success_gate",
            ],
        ),
        "## Robustness And Generalization Registry",
        "",
        markdown_table(
            planned_robustness,
            [
                "experiment_id",
                "architecture",
                "dataset",
                "methods",
                "primary_metric",
                "matched_controls",
                "success_gate",
            ],
        ),
        "## Peer Spiking Transformer Context",
        "",
        markdown_table(
            peers,
            [
                "model",
                "year",
                "status",
                "attention_or_unit",
                "dataset",
                "time_steps",
                "reported_top1",
                "params_m",
                "lookup_dynamic_calibration",
                "source_url",
            ],
        ),
    ]
    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    snapshot = {
        "current_replacement_status": current,
        "experiment_registry": registry,
        "lookup_cost_proxy": lookup_cost,
        "peer_spiking_transformer_comparison": peers,
    }
    OUT_JSON.write_text(json.dumps(snapshot, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps({"markdown": str(OUT_MD.relative_to(ROOT)), "snapshot": str(OUT_JSON.relative_to(ROOT))}, sort_keys=True))


if __name__ == "__main__":
    main()
